#cloud-config
# vim: syntax=yaml
# examples:
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html

bootcmd:
  - echo 192.168.0.1 gw.homedns.xyz >> /etc/hosts
  - hostname tf-kvm-zabbix

runcmd:
  - apt-get --yes upgrade
  - apt-get --yes install 

ssh_pwauth: true

disable_root: false

chpasswd:
  list: |
     root:toor
     zabbix:zabbix123
  expire: false

users:
  - name: zabbix
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/zabbix
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDG3Zwb+uHG5afSfZ6RUSZ4Ub0SfDFh3Sn28Wwv2BNEiBgl0ex1ENIcX6H4SU+FHpOMosQIdtNoylqCStuKi1heXZ1m4cufFBa4dVfkfHpkDiMCZbKfDofZVLiKBXBuQhG08H+ZXsuExKIGnyl1to+0fDbTger7EdPaP9rxv/s0D/3f/FfaFVC3dsvl23xQgHQcTObt39kZ+gYuXtXhENYSG32IqSuz+w3HR3R54sZfIZSHNEr7xkrgxC0X/wFqyAbmbf2/iMtEpmHF80GoZa2LdHCd6IfoOC8G3T3/O6UeoNBwR4TqTCoY/om6O31voRd1CWmSLaG3is9X0ypQcllW4xq4MB7MRvpZ1UArLAIm7BtuveXB9zFvYfKt++AgZra+GAC05Dz5A1tuPkH3WXIgV8GRUa2eLe3RHvl3eXGPznctE3uVW/xk9OvYl4VMUiRqxLqaTteMqozx3ddApQKXZDAH5p4m90Ezh21cbDzaYe4MQd2C1dVtIGV8/8p/6ul51KjEma1iWc3g/1436CT7Rde4l8mmaOzZbPQupMr1r3vMmFdQ6eEbf3qdyiv5R9RGf9ecqmU+ygGAwI75sQ2gAZ5wBqV6CO3HpIQ4kNkuvAHA3wolP8fHvdGb5Gfh3AnLZ36FgM3YKf5/P2nhXmvDBC+vlECgLEZtgvvaOKt2qw== Debian Desktop access host tf-kvm-zabbix

packages:
  - python3
  - python2-minimal
  - cmatrix
  - ethstatus
  - s-tui
  - lm-sensors
  - neofetch
  - dnsutils
  - htop

package_update: true

package_upgrade: true

#package_reboot_if_required: true

#final_message: "The system is finally up, after $UPTIME seconds"